services:
  - type: web
    name: writersnite-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://writersnite.vercel.app
      - key: ADMIN_EMAILS
        value: scurd142@gmail.com
      - key: SITE_URL
        value: https://writersnite.vercel.app
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://writersnite.vercel.app
      - key: CORS_ORIGIN
        value: https://writersnite.vercel.app,http://localhost:3000
