-- Remove WritersNite-specific tables and enums

-- Drop dependent tables first
DROP TABLE IF EXISTS "BlogPostTag" CASCADE;
DROP TABLE IF EXISTS "BlogPost" CASCADE;
DROP TABLE IF EXISTS "BlogTag" CASCADE;
DROP TABLE IF EXISTS "BlogCategory" CASCADE;
DROP TABLE IF EXISTS "Testimonial" CASCADE;
DROP TABLE IF EXISTS "UserAchievement" CASCADE;
DROP TABLE IF EXISTS "Achievement" CASCADE;
DROP TABLE IF EXISTS "UserGamification" CASCADE;
DROP TABLE IF EXISTS "TestResult" CASCADE;
DROP TABLE IF EXISTS "WritingTest" CASCADE;
DROP TABLE IF EXISTS "Resource" CASCADE;
DROP TABLE IF EXISTS "Invoice" CASCADE;
DROP TABLE IF EXISTS "JobSubmission" CASCADE;
DROP TABLE IF EXISTS "Job" CASCADE;
DROP TABLE IF EXISTS "Subscription" CASCADE;

-- Drop WritersNite enums
DROP TYPE IF EXISTS "JobCategory" CASCADE;
DROP TYPE IF EXISTS "JobStatus" CASCADE;
DROP TYPE IF EXISTS "JobSubmissionStatus" CASCADE;
DROP TYPE IF EXISTS "WriterRank" CASCADE;
DROP TYPE IF EXISTS "SubscriptionStatus" CASCADE;

-- Add EliteBet wallet fields
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "casinoBalance" DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE "Wallet" ADD COLUMN IF NOT EXISTS "bonusBalance" DECIMAL(18,2) NOT NULL DEFAULT 0;

-- Add EliteBet user fields
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "promoCode" TEXT;

-- Update default currency to KES
ALTER TABLE "Wallet" ALTER COLUMN "currency" SET DEFAULT 'KES';
ALTER TABLE "Payment" ALTER COLUMN "currency" SET DEFAULT 'KES';
ALTER TABLE "Withdrawal" ALTER COLUMN "currency" SET DEFAULT 'KES';
